[features]
seeds = false
skip-lint = false

[programs.localnet]
kudos_program = "FrR535wDsm4PUEU41ipJRMWYJj4bMoQX6GPqiKfQdgzU"

[programs.devnet]
kudos_program = "FrR535wDsm4PUEU41ipJRMWYJj4bMoQX6GPqiKfQdgzU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ashwin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
